name: Maven with NVS

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn package dependency:copy-dependencies
    - name: Nexus Vulnerability Scanner
      uses: sonatype/nvs-github-action@releases/v1.0.0
      with:
        email: ${{ secrets.NVS_SCANNER_EMAIL }}
        password: ${{ secrets.NVS_SCANNER_PASSWORD }}
        directory: ./target/
