name: Build and Validate

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn clean install
    - name: Run NVS
      uses: sonatype/nvs-github-actions@v1
      with:
        email: mshevelov@sonatype.com
        password: admin123
        directory: target
    
